custom_env: 
  barrel_pos_noise: 0.5
  barrel_stacking_noise: 0.1
  box:
    colour: 0.3 0.3 0.3 1
    x: 1.0
    y: 1.0
    z: 1.0
  cylinder:
    colour: 0.5 0.6 0.5 1
    r: 0.4
    z: 0.6
  heights:
    '100': 1
    '180': 2
    '255': 3
  input_map: src/gazebosim_world_generator/maps/custom_env.tiff
  map_centre:
    x: 32
    y: 32
  map_evolution:
    number_of_barrels_to_remove: 3
    number_of_blocks_to_remove: 2
    number_of_extra_barrels: 3
    number_of_extra_blocks: 2
  metres_per_pixel: 0.5
  output_config_file_name: src/gazebosim_world_generator/worlds/custom_env/custom_env.yaml
  output_filename: src/gazebosim_world_generator/worlds/custom_env/custom_env.world
  output_map: src/gazebosim_world_generator/worlds/custom_env/custom_env.tiff
  output_radiation_filename: src/gazebosim_world_generator/worlds/custom_env/radiation.yaml
  radiation_map: None
  radiation_output_file_format: 0
  radiation_scaling: 1.0
  radiation_units_alpha: Sv/h
  radiation_units_beta: Sv/h
  radiation_units_gamma: Sv/h
  sizing:
    '0': 1.0
    '100': 0.25
    '180': 0.5
    '255': 1.0
  templates_folder: src/gazebosim_world_generator/templates/
  walls:
    colour: 0.7 0.7 0.7 1
    height: 3.0
  custom_models:
    bookshelf:
      name: bookshelf
      value: 200 200 200
      z_offset: 0.0
      dae_location: "/home/tom/ROS/Oxford/catkin_ws/src/gazebosim_world_generator/meshes/bookshelf.dae"
      pose_noise: 0.00      
    chair:
      name: chair
      value: 50 200 200
      z_offset: 0.0
      dae_location: "/home/tom/ROS/Oxford/catkin_ws/src/gazebosim_world_generator/meshes/chair.dae"
      pose_noise: 0.00      
    desk:
      name: desk
      value: 200 50 200
      z_offset: 0.0
      dae_location: "/home/tom/ROS/Oxford/catkin_ws/src/gazebosim_world_generator/meshes/desk.dae"
      pose_noise: 0.00      
    table:
      name: table
      value: 200 200 50
      z_offset: 0.0
      dae_location: "/home/tom/ROS/Oxford/catkin_ws/src/gazebosim_world_generator/meshes/table.dae"
      pose_noise: 0.00      
